### ISSUE TITLE
DOC: Getting started; Typo in Readme? 

### ISSUE THREAD

**Issue by AnneTheAgile** [walidsa3d/cookiecutter-pyoneer#3]
hi! this looks like a great idea. 
I am confused by the readme. 

1.To install, don't you mean to git clone, not call cookiecutter? 
````
## Installation
$ cookiecutter git@github.com:walidsa3d/cookiecutter-pyoneer.git
```
2.To run, I do not see where a script lives in this repo?
````
## Usage
$ cookiecutter cookiecutter-pyoneer
```
ty!

**Comment by walidsa3d** [comment]
First you have to install cookiecutter : pip install cookiecutter
Then install the template locally (which will clone it somewhere) :  cookiecutter git@github.com:walidsa3d/cookiecutter-pyoneer.git
Then every time you want to start a new project call the template :  cookiecutter cookiecutter-pyoneer
